name: Deploy
on:
  workflow_run:
    workflows: 
      - "Build and push docker image"
    branches:
      - main
    types: 
      - completed

jobs:
  docker-back-end:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: echo 'hi'