name: Build and push docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-back-end:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker build
        working-directory: .
        run: docker build -t ghcr.io/creative-nest/creative-nest .
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker push
        run: docker push ghcr.io/creative-nest/creative-nest